image: basic-debian-8:latest
stages:
    - deploy
before_script:
    - 'which sshpass || ( apt-get update -y && apt-get install sshpass -y )'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
dev:
    stage: deploy
    environment: dev
    script:
        - sshpass -p $SSH_PASSWORD rsync -riz --delete -e "ssh" ./html/ $SSH_USERNAME@$SSH_HOST:$SSH_DIRECTORY
    only:
        - master
