<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 17.08.2017
 * Time: 16:04
 */

// declare(strict_types=1);


namespace app\widgets\breadcrumbs;


use Yii;
use yii\base\InvalidConfigException;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

class BreadcrumbsMandatoryHomeWidget extends Breadcrumbs
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!is_array($this->links)) {
            throw new InvalidConfigException(static::class . '::links must be set as array');
        }
    }

    /**
     * Renders the widget.
     */
    public function run()
    {
        $links = [];
        if ($this->homeLink === null) {
            $links[] = $this->renderItem([
                'label' => Yii::t('yii', 'Home'),
                'url' => Yii::$app->homeUrl,
            ], $this->itemTemplate);
        } elseif ($this->homeLink !== false) {
            $links[] = $this->renderItem($this->homeLink, $this->itemTemplate);
        }
        foreach ($this->links as $link) {
            if (!is_array($link)) {
                $link = ['label' => $link];
            }
            $links[] = $this->renderItem($link, isset($link['url']) ? $this->itemTemplate : $this->activeItemTemplate);
        }
        echo Html::tag($this->tag, implode('', $links), $this->options);
    }
}