<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 24.07.2017
 * Time: 18:54
 */

// declare(strict_types=1);


namespace app\modules\document\commands;


use app\modules\document\models\Document as DocumentModel;
use yii\console\Controller;

/**
 * Class Document
 * @package app\modules\document\commands
 */
class DocumentController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        ini_set('memory_limit', '150M');
    }


    /**
     *
     */
    public function actionDelete()
    {

        $documentsBatch = DocumentModel::find()->batch(100);

        /** @var DocumentModel[] $documents */
        foreach ($documentsBatch as $documents) {
            foreach ($documents as $document) {
                $this->stdout('Document ID:' . $document->id . PHP_EOL);
                foreach ($document->files as $file) {
                    $this->stdout('File ID:' . $file->id . PHP_EOL);
                    $file->delete();
                }
                $document->delete();
            }
        }

    }
}